name = "NamedGraphs"
uuid = "678767b0-92e7-4007-89e4-4527a8725b19"
authors = ["Matthew Fishman <mfishman@flatironinstitute.org>, Joseph Tindall <jtindall@flatironinstitute.org> and contributors"]
version = "0.8.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleGraphAlgorithms = "41400c72-0c58-5c16-8579-4ecbce768449"
SimpleGraphConverter = "205b04f2-f585-4877-a239-566270b3f673"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[weakdeps]
GraphsFlows = "06909019-6f44-4949-96fc-b9d9aaa02889"
KaHyPar = "2a6221f6-aa48-11e9-3542-2d9e0ef01880"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
SymRCM = "286e6d88-80af-4590-acc9-0001b223b9bd"

[extensions]
NamedGraphsGraphsFlowsExt = "GraphsFlows"
NamedGraphsKaHyParExt = "KaHyPar"
NamedGraphsMetisExt = "Metis"
NamedGraphsSimpleGraphAlgorithmsExt = "SimpleGraphAlgorithms"
NamedGraphsSymRCMExt = "SymRCM"

[compat]
AbstractTrees = "0.3, 0.4"
Combinatorics = "1.0.2"
Dictionaries = "0.4"
Graphs = "1.8"
GraphsFlows = "0.1.1"
KaHyPar = "0.3.1"
LinearAlgebra = "1.7"
Metis = "1.4"
PackageExtensionCompat = "1"
SimpleGraphAlgorithms = "0.6.0"
SimpleGraphConverter = "0.1.0"
SimpleTraits = "0.9"
SparseArrays = "1.7"
SplitApplyCombine = "1.2.2"
Suppressor = "0.2"
SymRCM = "0.2.1"
julia = "1.7"

[extras]
GraphsFlows = "06909019-6f44-4949-96fc-b9d9aaa02889"
KaHyPar = "2a6221f6-aa48-11e9-3542-2d9e0ef01880"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
SimpleGraphAlgorithms = "41400c72-0c58-5c16-8579-4ecbce768449"
SimpleGraphConverter = "205b04f2-f585-4877-a239-566270b3f673"
SymRCM = "286e6d88-80af-4590-acc9-0001b223b9bd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
