[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
NamedGraphs = "678767b0-92e7-4007-89e4-4527a8725b19"

[compat]
Documenter = "1.10"
Literate = "2.20.1"
NamedGraphs = "0.9"
